# Generated by Django 2.2.10 on 2020-04-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('proview', models.CharField(max_length=100)),
            ],
        ),
    ]
